# Generated by Django 2.0 on 2017-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
