# Generated by Django 2.0 on 2017-12-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0002_note_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
