# Generated by Django 2.0 on 2017-12-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0003_auto_20171224_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': ['-date_from'], 'ordering': ['date_from']},
        ),
        migrations.AlterModelOptions(
            name='deadline',
            options={'get_latest_by': ['-date_scheduled'], 'ordering': ['date_scheduled']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': ['-date_from'], 'ordering': ['date_from']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'get_latest_by': ['-date_scheduled'], 'ordering': ['date_scheduled']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['date_modified']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ['-date_scheduled'], 'ordering': ['date_scheduled']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_text',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadline_text',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_text',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
