# Generated by Django 2.0 on 2017-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0004_auto_20171228_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
