# Generated by Django 2.0 on 2018-01-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_text', models.CharField(max_length=100, verbose_name='Description')),
                ('date_scheduled', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField()),
            ],
            options={
                'ordering': ['date_scheduled'],
                'get_latest_by': ['-date_scheduled'],
            },
        ),
    ]
